# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/graph_builder.ipynb.

# %% auto 0
__all__ = ['NEO4J_URI', 'NEO4J_USER', 'NEO4J_PASSWORD', 'driver', 'create_node', 'create_edge']

# %% ../nbs/graph_builder.ipynb 0
from neo4j import GraphDatabase

import os
import numpy as np 


# %% ../nbs/graph_builder.ipynb 1
from dotenv import load_dotenv
load_dotenv()
NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USER = os.getenv("NEO4J_USER")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")

driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))

# %% ../nbs/graph_builder.ipynb 2
def create_node(tx, label, properties):
    prop_str = ', '.join(f'{k}: ${k}' for k in properties)
    query = f"CREATE (n:{label} {{{prop_str}}})"
    tx.run(query, **properties)


def create_edge(tx, from_id, to_id, rel_type):
    query = (
        "MATCH (a), (b)"
        "WHERE id(a) = $from_id AND id(b) = $to_id"
        "CREATE (a)-[:{rel_type}]->(b)"
    )
    tx.run(query, from_id=from_id, to_id=to_id)



# %% ../nbs/graph_builder.ipynb 3
with driver.session() as session:
    session.write_transaction(create_node, "User", {"name": "Alice"})
    session.write_transaction(create_node, "Item", {'name':'Laptop'})

driver.close()
