# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/generative-ai',
                'doc_host': 'https://karanyadav14.github.io',
                'git_url': 'https://github.com/karanyadav14/generative-ai',
                'lib_path': 'recommender_system'},
  'syms': { 'recommender_system.gnn_recommender': { 'recommender_system.gnn_recommender.SimpleGCN': ( 'gnn_recommender.html#simplegcn',
                                                                                                      'recommender_system/gnn_recommender.py'),
                                                    'recommender_system.gnn_recommender.SimpleGCN.__init__': ( 'gnn_recommender.html#simplegcn.__init__',
                                                                                                               'recommender_system/gnn_recommender.py'),
                                                    'recommender_system.gnn_recommender.SimpleGCN.forward': ( 'gnn_recommender.html#simplegcn.forward',
                                                                                                              'recommender_system/gnn_recommender.py'),
                                                    'recommender_system.gnn_recommender.fetch_graph': ( 'gnn_recommender.html#fetch_graph',
                                                                                                        'recommender_system/gnn_recommender.py')},
            'recommender_system.graph_builder': { 'recommender_system.graph_builder.create_edge': ( 'graph_builder.html#create_edge',
                                                                                                    'recommender_system/graph_builder.py'),
                                                  'recommender_system.graph_builder.create_node': ( 'graph_builder.html#create_node',
                                                                                                    'recommender_system/graph_builder.py')}}}
